### ISSUE TITLE
MPU9250BasicAHRS.ino Arduino: 'MahonyQuaternionUpdate' was not declared in this scope

### ISSUE THREAD

**Issue by jonathanrjpereira** [shubhampaul/Real_Time_Planet_Tracking_System#1]
C:\Users\Jonathan\Documents\Arduino\libraries\Real_Time_Planet_Tracking_System-master\MPU9250BasicAHRS.ino\MPU9250BasicAHRS.ino.ino: In function 'void loop()':

MPU9250BasicAHRS.ino:399: error: 'MahonyQuaternionUpdate' was not declared in this scope

   MahonyQuaternionUpdate(ax, ay, az, gx*PI/180.0f, gy*PI/180.0f, gz*PI/180.0f, my, mx, mz);

                                                                                          ^

exit status 1
'MahonyQuaternionUpdate' was not declared in this scope

**Comment by shubhampaul** [comment]
It is because the fuction "MahonyQuaternionUpdate" is in the quaternion_filters.ino file. It would be better if you copy and paste the whole file into MPU9250BasicAHRS.ino (merge both files).
